language: node_js
node_js:
  - 4.4
  - 5.8

services:
  - mongodb

env:
  - MONGO_TAILOR_TEST_URI=mongodb://localhost:27017/?replicaSet=auth

before_install:
  - echo "replSet = auth" | sudo tee -a /etc/mongodb.conf
  - sudo service mongodb restart
  - sleep 20
  - mongo --eval 'rs.initiate()'
  - sleep 15

before_script:
  - "until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done"

script: "make test"
